services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
    environment:
      - SCALER_FILE=/models/scaler.pkl
      - LR_MODEL_FILE=/models/linear_regression.pkl
      - IMPUTATION_FILE=/models/imputer_pipeline.pkl